INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (1,'Ananth','Electro Fields','test_1','2021-07-16',100);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (2,'Bhagath','Electro Fields','test_1','2021-07-16',78);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (3,'Chaya','Electro Fields','test_1','2021-07-16',68);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (4,'Esharath','Electro Fields','test_1','2021-07-16',87);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (5,'Bhagath','Electro Fields','quiz_1','22-07-16',20);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (6,'Chaya','Electro Fields','lab_1','2023-07-16',10);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (7,'Ananth','Electro Fields','project_1','2022-07-16',100);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (8,'Davanth','Electro Fields','project_1','2022-07-16',100);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (9,'Bhagath','Electro Fields','quiz_2','2022-07-16',50);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (10,'Ananth','Electro Fields','quiz_1','2022-07-16',100);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (11,'Bhagath','Electro Fields','lab_1','2022-07-16',10);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (12,'Chaya','Electro Fields','project_1','2022-07-16',100);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (13,'Bhagath','Electro Fields','project_1','2022-07-16',100);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (14,'Ananth','Computing Techniques','test_1','2022-07-16',86);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (15,'Ananth','Electro Fields','quiz_2','2022-07-16',100);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (16,'Bhagath','Computing Techniques','project_1','2022-07-16',100);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (17,'Ananth','Electro Fields','lab_1','2022-07-16',100);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (18,'Chaya','Computing Techniques','quiz_1','2022-07-16',20);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (19,'Ananth','Electro Fields','test_2','2022-08-16',100);
INSERT INTO STUDENT_SCORE (STUDENT_ID,NAME,SUBJECT,CATEGORY,SUBMISSION_DATE,POINTS ) VALUES (20,'Chaya','Electro Fields','test_2','2022-08-16',92);



INSERT INTO ASSIGNMENT_CATEGORY (CATEGORY_ID,CATEGORY_TYPE,CATEGORY_WEIGHT ) VALUES (1,'test','40');
INSERT INTO ASSIGNMENT_CATEGORY (CATEGORY_ID,CATEGORY_TYPE,CATEGORY_WEIGHT ) VALUES (2,'lab','10');
INSERT INTO ASSIGNMENT_CATEGORY (CATEGORY_ID,CATEGORY_TYPE,CATEGORY_WEIGHT ) VALUES (3,'quiz','20');
INSERT INTO ASSIGNMENT_CATEGORY (CATEGORY_ID,CATEGORY_TYPE,CATEGORY_WEIGHT ) VALUES (4,'project','30');
